### ISSUE TITLE
Sonarr & Radarr v3 Settings

### ISSUE THREAD

**Issue by ByronBlackbeard27** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#1]
Good day,
Is there not different settings for V3 of Radarr & Sonarr - I changed the search path to "/add/new/" instead of the default "/addseries/", but cant figure out the Search field selector/jquery selector.

Thanks for the great extension, I've been longing for this.

Thanks

**Comment by trossr32** [comment]
Hi,

I'm running these on a Qnap @ version 2 so haven't tested version 3 yet. I'll get them installed on a PC this evening and do some testing, bear with me 👍

**Comment by trossr32** [comment]
The selector you're looking for is:

input[class*="AddNewSeries/searchInput"]

Tested working with v3 of Sonarr. I'll leave this ticket open for now and close when I've added some comments to the extension to help other users facing the same issue.

Thanks for raising this.

**Comment by trossr32** [comment]
Extension updated and awaiting review in Chrome and Edge stores.

**Comment by Aerya** [comment]
Hi,

Does this still work for any of you? It's doesn't on my side. Nothing is passed to Sonarr nor Radarr.
https://i.imgur.com/qlUnpQE.png

Thanks,

**Comment by trossr32** [comment]
Hi @Aerya, 

I'll set up an instance of V3 of Sonarr this weekend and do some testing. In the meantime if you're able to provide the following that would really help me recreate your scenario:

- OS and version
- Browser and version
- Sonarr/Radarr versions

Thanks 👍

**Comment by ByronBlackbeard27** [comment]
Hi there,

I've been having the same issue for a while. My details:

**OS:** Windows 10 Pro (Build 19041)
**Browser:** Edge (Version 84.0.522.52)
**Sonarr Version:** 3.0.4.982 (phantom-develop)
**Radarr Version:** 3.0.0.3943 (nightly)
**Lidarr Version:** 0.8.0.1877 (nightly)

I understand that I'm on the beta versions of Sonarr/Radarr/Lidarr, therefor I just disabled the extension in my browser when I saw it wasn't working anymore. 

Thanks for your help. I really like this extension.

**Comment by Aerya** [comment]
I use Linuxservers builds for both, based on Ubuntu: https://hub.docker.com/r/linuxserver/radarr & https://hub.docker.com/r/linuxserver/radarr

Browser: Firefox 81.0 (64 bits) (Linux)
Sonarr Version: 3.0.4.982 (phantom-develop)
Radarr Version: 3.0.0.3943 (nightly)

**Comment by trossr32** [comment]
Hi @Aerya @ByronBlackbeard27 

I've tested using the latest version of Sonarr, Radarr and Lidarr from linuxserver.io and these are the revised settings required to make the extension work with them. These need to be amended in the extension Settings > Advanced tab > Search field selector field (make sure you press save at the bottom of the settings page after updating these fields):

Radarr 3.0.0.3954 - **input[name="movieLookup"]**
Sonarr 3.0.4.982 - **input[name="seriesLookup"]**
Lidarr 0.8.0.1881 - **input[name="searchBox"]**

Let me know if you have any issues after you have applied these settings.

I'll update the documentation for the extension and publish new versions for all browsers, but that might take me a couple of days. I think I'll also put a guide together to enable people to work these out for themselves if they change again, but that does require knowledge of jQuery selectors so might not be too helpful for many.

If you ever see this break again, please raise a new issue (rather than reopening this one) and I'll try and get revised settings for you asap. I have these latest versions set up in docker now so it should be a quick turnaround.

If you have the time, I'd really appreciate a positive rating/review in whichever browser extension store you're using; it's currently sitting at 1 star on the chrome web store because one guy didn't see the benefit of the extension and left a poor review 🙄 

I appreciate you getting in touch and bringing this to my attention, and hope you continue to find the extension useful 🙂

**Comment by Aerya** [comment]
Works like a charm, thank you !! :)
