### ISSUE TITLE
Support for IMDB reference page

### ISSUE THREAD

**Issue by tr0nllam** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#130]
Could you add support for the icon to appear next to the title when viewing the IMDB reference version of the standard TV Show/Movie page? Currently, the icon does not appear unless you use the custom icon option.

**Comment by trossr32** [comment]
Not sure what a reference version is, can you provide an example?

**Comment by tr0nllam** [comment]
https://www.imdb.com/title/tt4154796/reference/

**Comment by trossr32** [comment]
This occurs because the imdb integration looks for an h1 element to put the icon in when not using custom icons, and the reference pages use an h3 element for the title. I don't really want to duplicate the functionality for h3 elements too as then there'll be issues with multiple icons appearing.

Sorry, closing without a fix.
