### ISSUE TITLE
Not Searching Sonarr/Radarr

### ISSUE THREAD

**Issue by StraightSpine** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#196]
**Describe the bug**
When opening Radarr/Sonarr from the respective icon on IMDb & TMDB, the search page is opened but the search field is not populated. The IMDB/TMDB reference appears in the url. 

I expect the show to be searchged and to show in the Search field in Radarr/Sonarr. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to (https://www.imdb.com/title/tt0795176/?ref_=chttvtp_t_3)
2. Click on the Sonarr Icon

**Desktop (please complete the following information):**
 - OS: W11
 - Browser: Firefox
 - Version: 126.0
 - Extension version: Version 2.8.8

**Screenshots**
![2024-05-29 12_32_37-Add New Series - Sonarr — Mozilla Firefox](https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/assets/171114005/c9ecd19c-ef3a-4879-941a-d548549e88fb)
![2024-05-29 12_32_18-Planet Earth (TV Mini Series 2006) - IMDb — Mozilla Firefox](https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/assets/171114005/59b20e21-de3a-4183-998e-8565861a0cbd)

**Comment by StraightSpine** [comment]
![Uploading 2024-05-29 12_34_15-Servarr autosearch options — Mozilla Firefox.png…]()

**Comment by notjhoan** [comment]
I've got the exact same issue with Chrome.

**Comment by dynamiccookies** [comment]
This is happening to me too, and the cause is here:
https://github.com/trossr32/sonarr-radarr-lidarr-autosearch-browser-extension/blob/b56ef300c41ff7673700758d9117c6fbd4cb5bc7/src/content/js/content_script.js#L1513

`encodeURIComponent(searchTerm)` is replacing the colon with "%3A".

One solution could be to replace the "%3A" with a colon after the encoding is completed:
`site.searchPath + encodeURIComponent(searchTerm).replace(/\./g, ' ').replace(/%3A/g, ':')`
