### ISSUE TITLE
Add MusicBrainz as a source

### ISSUE THREAD

**Issue by StormPooper** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#25]
Since Lidarr uses MusicBrainz as the source of its metadata, it would be really useful to be able to add an artist from MusicBrainz.

**Comment by trossr32** [comment]
Added integration to MusicBrainz artist pages as requested.

Submitted to all web extension stores as version 1.4.0, so will be available when the new version has passed reviews.

**Comment by StormPooper** [comment]
Awesome, thanks for the quick turnaround, much appreciated - tested on Firefox and working great.

I do have one minor suggestion though, I notice you're selecting `a > bdi` for the title, it might be worth just doing `a` so it includes the comment in order to match the exact artist.

For example, if I click the icon on [Zapp (US funk band)](https://musicbrainz.org/artist/e89e79d4-04c1-4bc3-9be1-a15899c93d8f) the top result in Lidarr for "Zapp" is actually "Zapp Zapp" instead of "Zapp (US funk band)", but if it searched for "Zapp (US funk band)" then it is the top result.

Very minor issue though. Again, thanks for updating it so quickly.

**Comment by trossr32** [comment]
No problem, and thanks for the suggested upgrade.

I think the best option would be to refactor so that the extension can pick
up the musicbrainz id and search lidarr with that to get an exact match,
but I wanted to get it sorted quickly whilst I had some time this evening
and the changes I made for v1.4.0 fit into the existing framework easily.

I'll raise another issue for that and try to address soon. Glad you're
getting some use out of the extension 👍

**Comment by StormPooper** [comment]
That makes sense, nice one.
