### ISSUE TITLE
Radarr settings saying "failed, please double check the domain and API key" even though both are correct

### ISSUE THREAD

**Issue by alexander-paterson** [trossr32/sonarr-radarr-lidarr-autosearch-browser-extension#71]
I still seem to be able to search for movies using either the icon on the website and/or the right-click menu so I assume the details are correct and there is just a bug on the settings page of the extension?

**Comment by trossr32** [comment]
This is working fine for me so can't recreate. 

You can test your own instance api by putting the following in your browser (assuming this is for sonarr, replace parts in square brackets):

**http://[sonarr.domain]:8989/api/system/status?apikey=[api key]**

You should receive a JSON response which will include a version property. If you don't get a JSON response there's something going on with your instance (proxy? permissions?).

If you do get a JSON response but the extension is still not working, could you please provide the JSON response you get (at least the version property if you're not comfortable sharing the whole response).

**Comment by alexander-paterson** [comment]
That doesn't seem to work.

I'm running Radarr in Docker and it has a different port but I don't think that should make a difference. Sonarr is running the same way and I can do the same with that and get a response.

Guess this can be closed since it appears to be a problem with something on my end.

**Comment by trossr32** [comment]
I'm running Radarr in docker too, so you're correct that shouldn't be your issue. Hope you get it sorted.

**Comment by bifa2** [comment]
I'm hitting this issue too.

http://localhost:7878/api/system/status?apikey=removed = fails

http://localhost:7878/api/v3/system/status?apikey=removed = works

Does this extension need updating to look to `v3`? Seems like Radarr version 4 doesn't use the old API anymore.

**Comment by trossr32** [comment]
Strange. I've just tested and mine's working exactly the same (i.e. successfully) with either http://localhost:7878/api/system/status?apikey=removed or http://localhost:7878/api/v3/system/status?apikey=removed

Assuming you meant 'version 3' in your comment rather than 'version 4'?

I guess I could adapt the code to try both variations, but would like a confirmation that's definitely the issue you're seeing before I go ahead if possible.

Alternatively I could make the URL stub of the API configurable and default it to the current setting so you could change for testing?

**Comment by bifa2** [comment]
Hi, thanks for the prompt reply :)

Radarr is version 4 now: https://github.com/Radarr/Radarr/releases but uses `v3` for the API (separate product and API versioning basically). 

As per the changelog notes for Radarr version 4, they've deprecated the legacy API: [b7f3791 New: Remove Legacy API](https://github.com/Radarr/Radarr/commit/b7f379196696c429315d729ca811f4f53c7120f4).

It was released 18 hours ago which is why my PowerShell/Radarr integration broke last night (I wasn't using the `v3` API) but I only stumbled across this extension today so I can't explain why OP had a problem previously (even though our problem seems to the same). Maybe the version used in the Docker container uses preview branches or something (I'm on `develop` according to the GUI).

**Comment by bifa2** [comment]
Ah yes, version 4 doesn't appear to have been merged into the master branch yet! I assume you're on master :)

**Comment by trossr32** [comment]
Yes I'm just using the master branch and wasn't intending to support any preview branches really. 

I'll leave this open and look into making the change to configure the API URL anyway as it may help with the V4 cross-over. Thanks for raising and clarifying 👍

**Comment by trossr32** [comment]
v4 of Radarr should work with release v2.3.2

**Comment by bifa2** [comment]
Confirmed, all good for me.
